<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyPhongMay" Class="QuanLyPhongNetDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-UCLG3AIH\SQLEXPRESS;Initial Catalog=QuanLyPhongMay;Integrated Security=True" SettingsObjectName="QuanLyPhongNet.DAL.Properties.Settings" SettingsPropertyName="QuanLyPhongMayConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BeforePayClient" Member="BeforePayClients">
    <Type Name="BeforePayClient">
      <Column Name="ClientID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BillID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StartTime" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="UseTime" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="LeftTime" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Association Name="Bill_BeforePayClient" Member="Bill" ThisKey="BillID" OtherKey="BillID" Type="Bill" IsForeignKey="true" />
      <Association Name="Client_BeforePayClient" Member="Client" ThisKey="ClientID" OtherKey="ClientID" Type="Client" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TransactionDiary" Member="TransactionDiaries">
    <Type Name="TransactionDiary">
      <Column Name="UserID" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MemberID" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="TransacDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AddTime" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="AddMoney" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="UseTime" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(120)" CanBeNull="true" />
      <Association Name="Member_TransactionDiary" Member="Member" ThisKey="MemberID" OtherKey="PhoneNumber" Type="Member" IsForeignKey="true" />
      <Association Name="TheUser_TransactionDiary" Member="TheUser" ThisKey="UserID" OtherKey="UserID" Type="TheUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Bill" Member="Bills">
    <Type Name="Bill">
      <Column Name="BillID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FoundedUserID" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="FoundedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PriceTotal" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Bill_BeforePayClient" Member="BeforePayClients" ThisKey="BillID" OtherKey="BillID" Type="BeforePayClient" />
      <Association Name="TheUser_Bill" Member="TheUser" ThisKey="FoundedUserID" OtherKey="UserID" Type="TheUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Category_Drink" Member="Drinks" ThisKey="CategoryName" OtherKey="CategoryName" Type="Drink" />
      <Association Name="Category_Food" Member="Foods" ThisKey="CategoryName" OtherKey="CategoryName" Type="Food" />
      <Association Name="Category_TheCard" Member="TheCards" ThisKey="CategoryName" OtherKey="CategoryName" Type="TheCard" />
    </Type>
  </Table>
  <Table Name="dbo.Client" Member="Clients">
    <Type Name="Client">
      <Column Name="ClientID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StatusClient" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RoomID" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="Client_BeforePayClient" Member="BeforePayClients" ThisKey="ClientID" OtherKey="ClientID" Type="BeforePayClient" />
      <Association Name="Client_LoginMember" Member="LoginMembers" ThisKey="ClientID" OtherKey="ClientID" Type="LoginMember" />
      <Association Name="Client_OrderCard" Member="OrderCards" ThisKey="ClientID" OtherKey="Clientid" Type="OrderCard" />
      <Association Name="Client_OrderDrink" Member="OrderDrinks" ThisKey="ClientID" OtherKey="ClientID" Type="OrderDrink" />
      <Association Name="Client_OrderFood" Member="OrderFoods" ThisKey="ClientID" OtherKey="ClientID" Type="OrderFood" />
      <Association Name="Room_Client" Member="Room" ThisKey="RoomID" OtherKey="RoomID" Type="Room" IsForeignKey="true" />
      <Association Name="StatusClient_Client" Member="StatusClient1" ThisKey="StatusClient" OtherKey="StatusClient1" Type="StatusClient" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Drink" Member="Drinks">
    <Type Name="Drink">
      <Column Name="DrinkID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DrinkName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PriceUnit" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="UnitLot" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="InventoryNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Drink_OrderDrink" Member="OrderDrinks" ThisKey="DrinkID" OtherKey="DrinkID" Type="OrderDrink" />
      <Association Name="Category_Drink" Member="Category" ThisKey="CategoryName" OtherKey="CategoryName" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Food" Member="Foods">
    <Type Name="Food">
      <Column Name="FoodID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FoodName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PriceUnit" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="UnitLot" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="InventoryNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Food_OrderFood" Member="OrderFoods" ThisKey="FoodID" OtherKey="FoodID" Type="OrderFood" />
      <Association Name="Category_Food" Member="Category" ThisKey="CategoryName" OtherKey="CategoryName" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GroupClient" Member="GroupClients">
    <Type Name="GroupClient">
      <Column Name="GroupClientID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GroupClientName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Discription" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="GroupClient_GroupClientAndGroupUser" Member="GroupClientAndGroupUsers" ThisKey="GroupClientID" OtherKey="GroupClientID" Type="GroupClientAndGroupUser" />
      <Association Name="GroupClient_Room" Member="Rooms" ThisKey="GroupClientID" OtherKey="GroupClientID" Type="Room" />
    </Type>
  </Table>
  <Table Name="dbo.GroupClientAndGroupUser" Member="GroupClientAndGroupUsers">
    <Type Name="GroupClientAndGroupUser">
      <Column Name="GroupUserID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GroupClientID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GiaDichVu" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="GroupClient_GroupClientAndGroupUser" Member="GroupClient" ThisKey="GroupClientID" OtherKey="GroupClientID" Type="GroupClient" IsForeignKey="true" />
      <Association Name="GroupUser_GroupClientAndGroupUser" Member="GroupUser" ThisKey="GroupUserID" OtherKey="GroupUserID" Type="GroupUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GroupUser" Member="GroupUsers">
    <Type Name="GroupUser">
      <Column Name="GroupUserID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GroupUserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="GroupUser_GroupClientAndGroupUser" Member="GroupClientAndGroupUsers" ThisKey="GroupUserID" OtherKey="GroupUserID" Type="GroupClientAndGroupUser" />
      <Association Name="GroupUser_Member" Member="Members" ThisKey="GroupUserID" OtherKey="GroupUserID" Type="Member" />
      <Association Name="GroupUser_TheUser" Member="TheUsers" ThisKey="GroupUserID" OtherKey="GroupUserID" Type="TheUser" />
    </Type>
  </Table>
  <Table Name="dbo.LoginMember" Member="LoginMembers">
    <Type Name="LoginMember">
      <Column Name="MemberID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ClientID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StartTime" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="UseTime" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="LeftTime" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Association Name="Client_LoginMember" Member="Client" ThisKey="ClientID" OtherKey="ClientID" Type="Client" IsForeignKey="true" />
      <Association Name="Member_LoginMember" Member="Member" ThisKey="MemberID" OtherKey="PhoneNumber" Type="Member" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Member" Member="Members">
    <Type Name="Member">
      <Column Name="PhoneNumber" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AccountName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GroupUserID" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="CurrentTime" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="CurrentMoney" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="StatusAccount" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Member_TransactionDiary" Member="TransactionDiaries" ThisKey="PhoneNumber" OtherKey="MemberID" Type="TransactionDiary" />
      <Association Name="Member_LoginMember" Member="LoginMembers" ThisKey="PhoneNumber" OtherKey="MemberID" Type="LoginMember" />
      <Association Name="Member_MemberInformation" Member="MemberInformation" ThisKey="PhoneNumber" OtherKey="PhoneNumber" Type="MemberInformation" Cardinality="One" />
      <Association Name="GroupUser_Member" Member="GroupUser" ThisKey="GroupUserID" OtherKey="GroupUserID" Type="GroupUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MemberInformation" Member="MemberInformations">
    <Type Name="MemberInformation">
      <Column Name="PhoneNumber" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MemberName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FoundedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MemberAddress" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="Member_MemberInformation" Member="Member" ThisKey="PhoneNumber" OtherKey="PhoneNumber" Type="Member" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderCard" Member="OrderCards">
    <Type Name="OrderCard">
      <Column Name="Clientid" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CardID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PriceTotal" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Client_OrderCard" Member="Client" ThisKey="Clientid" OtherKey="ClientID" Type="Client" IsForeignKey="true" />
      <Association Name="TheCard_OrderCard" Member="TheCard" ThisKey="CardID" OtherKey="CardID" Type="TheCard" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderDrink" Member="OrderDrinks">
    <Type Name="OrderDrink">
      <Column Name="ClientID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DrinkID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PriceTotal" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Client_OrderDrink" Member="Client" ThisKey="ClientID" OtherKey="ClientID" Type="Client" IsForeignKey="true" />
      <Association Name="Drink_OrderDrink" Member="Drink" ThisKey="DrinkID" OtherKey="DrinkID" Type="Drink" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderFood" Member="OrderFoods">
    <Type Name="OrderFood">
      <Column Name="ClientID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FoodID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PriceTotal" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Client_OrderFood" Member="Client" ThisKey="ClientID" OtherKey="ClientID" Type="Client" IsForeignKey="true" />
      <Association Name="Food_OrderFood" Member="Food" ThisKey="FoodID" OtherKey="FoodID" Type="Food" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Room" Member="Rooms">
    <Type Name="Room">
      <Column Name="RoomID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoomName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GroupClientID" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="Room_Client" Member="Clients" ThisKey="RoomID" OtherKey="RoomID" Type="Client" />
      <Association Name="GroupClient_Room" Member="GroupClient" ThisKey="GroupClientID" OtherKey="GroupClientID" Type="GroupClient" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StatusClient" Member="StatusClients">
    <Type Name="StatusClient">
      <Column Name="StatusClient" Member="StatusClient1" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="StatusClient_Client" Member="Clients" ThisKey="StatusClient1" OtherKey="StatusClient" Type="Client" />
    </Type>
  </Table>
  <Table Name="dbo.TheCard" Member="TheCards">
    <Type Name="TheCard">
      <Column Name="CardID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CardName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PriceUnit" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="UnitLot" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="InventoryNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TheCard_OrderCard" Member="OrderCards" ThisKey="CardID" OtherKey="CardID" Type="OrderCard" />
      <Association Name="Category_TheCard" Member="Category" ThisKey="CategoryName" OtherKey="CategoryName" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TheUser" Member="TheUsers">
    <Type Name="TheUser">
      <Column Name="UserID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GroupUserID" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="TheUser_TransactionDiary" Member="TransactionDiaries" ThisKey="UserID" OtherKey="UserID" Type="TransactionDiary" />
      <Association Name="TheUser_Bill" Member="Bills" ThisKey="UserID" OtherKey="FoundedUserID" Type="Bill" />
      <Association Name="GroupUser_TheUser" Member="GroupUser" ThisKey="GroupUserID" OtherKey="GroupUserID" Type="GroupUser" IsForeignKey="true" />
    </Type>
  </Table>
</Database>